language: python
python:
  - "2.7"

# Cache PlatformIO packages using Travis CI container-based infrastructure.
sudo: false
cache:
  directories:
    - "~/.platformio"

env:
  - PLATFORMIO_CI_SRC=examples/BasicExample
  - PLATFORMIO_CI_SRC=examples/EventExample

install:
  - pip install -U platformio

script:
  - platformio ci --lib="." --board=uno --board=megaatmega1280 --board=megaatmega2560 --board=micro --board=leonardo

notifications:
  email:
    on_success: change
    on_failure: change
